# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70c54b370d33bf22c61793785b7b295613f5f75e01977cb84779473923434aa57fc27c1e322d38b8eec52f32045c5e19134c4658258f578cb394529cb23fc2c2

test:
  secret_key_base: dbef1368131414b7091ee265659e93987f1740b85a8543faba080dac47747bbbdb636a8a234f0c3de244aa70f00c460a7675a7105e12d403fef48e42c33962bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
